version: '3'
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=abhijeet
      - MONGO_INITDB_ROOT_PASSWORD=pass123
      

networks:
  project-name: